// Neue Version erstellen
// 1. Version hochstellen in Zeile 15
// 2. Version hochstellen in Zeile 25
// build.bat ausführen

include "conveyor.local.conf"

// Importiert JDK 17 von Amazon Corretto für ALLE Plattformen (Windows, macOS, Linux)
include "/stdlib/jdk/17/amazon.conf"

app {
  display-name = "Kartenverwaltung - Eltviller Carneval Verein"
  fsname = "ecv-karten"
  vendor = "Eltviller Carneval Verein"
  version = "0.1.0"

  license = "GPL-3.0-only"
  vcs-url = "https://github.com/SirEddington/Kartenverwaltung"

  // Java-Hauptklasse definieren
  jvm {
    main-class = "de.eltviller_carneval_verein.karten.MainApp"
  }

  inputs += target/Kartenverwaltung-0.1.0.jar

  site {
    base-url = "https://SirEddington.github.io/Kartenverwaltung"
  }

  // Windows-spezifische Optionen (greifen nur, wenn ein Tester auf Windows installiert)
  windows {
    dir-chooser = true
    per-user-install = true
    desktop-shortcut-prompt = true
    start-menu-shortcut = true
  }
}

conveyor.compatibility-level = 23